### ISSUE TITLE
Guide Feedback

### ISSUE THREAD

**Issue by jaydreyer** [api-evangelist/definitions#4]
Hi Kin,
Here's my ticky-tack copy-editor-ish feedback:

* Title page: Title - have the quote match up for Definition like they do for API
* Title page - The two paragraphs at the bottom should be left justified instead of centered.
* Title page - I'm confused about the last line of the paragraph on the right. I think the -- is throwing me off. Something doesn't flow right with it. Same thing with the 02 paragraph on page 2.
* Page 3 - "In this edition I am focusing" not "In this edition I a focusing"
* Page 3 - The second paragraph in the EDTRL. I would shorten it to "This guide is designed to be a summary of the world of API definitions, providing the reader with a recent summary of the variety of specifications that are defining the technology behind almost every part of our digital world."
* Page 5: Header - "central" misspelled. 
* Page 5: 2nd paragraph "documentation was even needed" to keep verb tense the same as "any code was written"
* Page 5: last paragraph should be "the world of API definitions"
* Page 6: On the left side of the page, Initiative is misspelled in "The Open API Initiative"
* Page 6: Last sentence of 1st paragraph, "it's" should be "its"
* Page 6: Second paragraph ends with two periods ..
* Page 7: Linking: "While" not "White", "pattern" not "patter"
* Page 7: 2nd to last paragraph "other changes that **are** moving the needle"
* Page 7: Last paragraph - the first sentence is a bit confusing. Maybe consider making it two sentences: "In 2017, the OpenAPI Spec is the clear leader of the API definitions format. It has the highest usage rate, as well as the largest number of tooling (or tools?) available."
* Page 8: The callout box on the lower left part of the page looks like it has the text cut off.
* Page 9: 1st full paragraph: "This type **of** approach", or, get rid of "type" and just say "This approach"
* Page 9: 4th paragraph "organizations" misspelled
* Page 9: Last paragraph - "...join the discussion about **the** next generation"
* Page 9: Last paragraph - consider removing one of the uses of "ground", probably the first one
* Page 10: first paragraph - should be "simplify", not "simplified"
* Page 10: last paragraph "leverages" is misspelled
* Page 11: 2nd paragraph "I will be working **to** add" not "to to"
* Page 11: 2nd paragraph "awareness" is misspelled
* Page 11: 2nd paragraph "proficiency" is misspelled
* Page 11: last paragraph "we have a lot of work ahead of **us**"
* Page 11: last paragraph Put a : after "There are two main ways to contribute to the building blocks of the web:"
* Page 12: first sentence, 1st paragraph, change "which" to "that"
* Page 12: Postman section: after together you have ".,"
* Page 12: Blueprint section "A couple of semantic assumptions" sentence doesn't make sense. Also, paragraph ends with ..
* Page 13: OData paragraph looks like it was cut off
* Page 13: ADMS section either got cut off or needs a period at the end
* Page 13: Docson paragraph is confusing. Maybe if you got rid of the "giving your JSON types" line. Or re-worded it.
* Page 14: "Negotiate" is misspelled in the "APIs should offer..." section
* Page 17: 1st paragraph. Remove the second instance of "currently". You should probably re-work this whole paragraph.
* Page 17: 2nd paragraph change "it's" to "its"
* Page 18: Change "have" to "has" in the sentence before 3Scale section. "Each" needs to agree with "has"
* Page 19: Grunt section "Specification" misspelled.
* Page 19: Paw section: I would change "and the Paw" to "with the Paw"
* Page 20: Subheading for Tooling - Parsers is cut off
* Page 20: Prance section: "provides" is misspelled
* Page 22: The subtitle to "About the Sponsors". I think you mean "Publication" and not "Public"
* Page 22: first paragraph should be "There are also regular updates"
* Page 22: Capitalize Definition in API Definition (since that's the name of your publication)
* Page 22: Left sidebar "Become **A** Sponsor". You left the .com out of your email address.
* Page 22: Left sidebar "Striking **A** Balance"

That's it! ;-)

Hope that helps. Let me know if you have questions. I did enjoy the doc and learned quite a few things. There's a lot going on in there!
-Jay
Twitter:@kaline

**Comment by kinlane** [comment]
Jay. You are my hero. I reflected every single change in the next draft. You provided it in such an easy way to find--I really, really appreciate it. Can I reference you in my credits?

**Comment by jaydreyer** [comment]
Awesome. Glad I could help! 

Sure. A reference is fine with me. Thanks!
