### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by spilio** [api-evangelist/definitions#5]
Excellent work @apievangelist - as always!  My proof reading feedback follows:

### OpenAPI Spec 3.0
* the first major ~~major~~ release

### Tooling
* In this edition ~~I a focusing~~ **am / will be** focusing on generating

## Page 5
*  of the world of API ~~efinitions~~  **d**efinitions

## Page 6
* Swagger ~~is~~ **has** now been reborn

### Components
* The new components architecture really reflects “APIs” ~~in my
opinion~~

>This whole publication reflects your opinions by default - no need
to repeat that ;)

### Linking
* giving a nod towards hypermedia design ~~patter~~ patter**n**

### Cookies
*  the new version allows for the ~~defining~~ **definition** of cookies

## Page 8
* quantifying the ~~compute~~ **computational**, storage, images, videos, and other essential *resources* powering

## Page 9
* This type **of** approach to delivering APIs
* The API-first approach to delivering human services also opens up
resources for inclusion in our applications and system**s**

## Page 10
* The modern API ~~leveragegs~~ **leverages**

## Page 14
* APIs should offer a range of media types allowing consumers to ~~negoiate~~ nego**t**iate the best content type for their needs

## Page 16
Doesn't seem to belong to particular section / topic

## Page 17
This page should go under the Services or Tooling section I guess

> API Transformer allows anyone to input a API Blueprint, Swagger 1.0 - 1.2, Swagger 2.0 JSON, Swagger 2.0 YAML, WADL - W3C 2009, WSDL - W3C, Google Discovery, RAML 0.8 1.0, I/O Docs - Mashery, HAR 1.2, Postman Collection 1.0 - 2.0, Mashape, or APIMATIC
Format API definition and then translate and export in a API Blueprint, Swagger 1.0 - 1.2, Swagger 2.0 JSON, Swagger 2.0 YAML, WADL - W3C 2009, RAML 0.8 - 1.0, Postman
Collection 1.0 - 2.0, and their own APIMATIC Format

I think this should be converted to a list

## Page 20

* Some of the tooling for parsing API ~~defini-~~ **definitions**
* Prances ~~provices~~ provi**d**es parsers for

## Page 22
* Those Who Make This ~~Public~~ **Publication** Possible

**Comment by kinlane** [comment]
Hey Chris,

Thank you so much. Tackled everything except 16 & 17....I agree that transformer should go under tooling and services, and it eventually will in future updates. I feel like API definition aggregation (page16) and API transofrmation (page17) go together, at least for my purposes here. With future editions it will shift.

I really appreciate you looking at this and providing feedback. Can I reference you or some project in the credits?

thanks as always -- Kin Lane

**Comment by spilio** [comment]
You're welcome Kin.  You can reference me if you like.  Thanks in advance.
