### ISSUE TITLE
API Definition guide feedback

### ISSUE THREAD

**Issue by aruckoj** [api-evangelist/definitions#7]
Great job, @apievangelist!

Here are some additional notes that weren't mentioned so far.

Let's start with several general topics that are based on my personal opinion:

- Long texts without hyphenation are easier to read, so it may be a good idea to remove it from the guide.
- Using two hyphens is quite common these days, but it may be more appropriate to replace them with long dashes instead. Long dash will be more familiar to wide audience. 
Same logic can be applied to using spaces around hyphens.

Going to particular pages:

- Page 1-2 - Having two similar blocks ("OpenAPI Spec 3.0" and "Human Services") on both first and second page is a bit confusing for me.
- Page 4 - Upside down text on the picture looks weird.
- Page 5 - In text "...specific standards such as PSD2 governing the banking sector, and Open Referral focused on delivering human services..." gaps are really small for me in PDF. Whole part is hard to read.
- Page 7 - Sentence "The latest version of the specification plays catch-up when it comes to allowing the body of a request and response to be defined separately from the request parameters, allowing for more control over the payload any API calls." seems tricky. Maybe you've meant "...more control over the payload OF any API calls."?
- Page 9 - In text "...services implementations are open and interoperable with other..." gaps are really small for me in PDF. Whole part is hard to read.
- Page 11 - Empty line at the top before "The Web Concepts project provides an overview..." seems redundant.
- Page 13 - Part that relates to "Open Data Protocol (OData)" ends up abruptly: "OData 
helps you focus on your business logic while building RESTful APIs without having to worry about the ".
- Page 14 - Part that relates to "text/tab-separated-values" doesn't end with a period, that is inconsistent with other parts on this page.
- Page 16 - Period isn't needed after "Voting Information Project".
- Page 17 - In text "...API Transformer allows anyone to input a API Blueprint, Swagger 1.0 - 1.2, Swagger 2.0 JSON, Swagger 2.0 YAML, WADL - W3C 2009, WSDL - W3C, Google Discovery, RAML 0.8 - 1.0, I/O Docs - Mashery, HAR 1.2, Postman Collection 1.0 - 2.0, Mashape, or APIMATIC Format API definition and then translate and export in a  API Blueprint, Swagger 1.0 - 1.2, Swagger 2.0 JSON, Swagger 2.0 YAML, WADL - W3C 2009, RAML 0.8 - 1.0, Postman Collection 1.0 - 2.0, and their own APIMATIC Format...." gaps are really small for me in PDF. Whole part is hard to read.

**Comment by kinlane** [comment]
Thank you so much...finally squeezing in time to conduct final edits. Tackling your feedback:

Long texts without hyphenation are easier to read, so it may be a good idea to remove it from the guide.

KL - I agree....took with what the template provided, and will be shifting in future versions.

Using two hyphens is quite common these days, but it may be more appropriate to replace them with long dashes instead. Long dash will be more familiar to wide audience. Same logic can be applied to using spaces around hyphens.

KL - Interesting. I will be working this into my approach, you are correct. Not sure why I type this way, where I learned this behavior. Shifting.

Page 1-2 - Having two similar blocks ("OpenAPI Spec 3.0" and "Human Services") on both first and second page is a bit confusing for me.

KL - I agree with this....I'm replacing with something on home page.....deciding what.

Page 4 - Upside down text on the picture looks weird.

KL - I see what you mean. Gonna just live with this one, as I'm hoping to get more graphical assistance in future. Meaning I am bad at this. ;-)

Page 5 - In text "...specific standards such as PSD2 governing the banking sector, and Open Referral focused on delivering human services..." gaps are really small for me in PDF. Whole part is hard to read.

KL - The formatting is a hard thing for me to adjust too. I changed a few words that expanded it a little, making more readable.

Page 7 - Sentence "The latest version of the specification plays catch-up when it comes to allowing the body of a request and response to be defined separately from the request parameters, allowing for more control over the payload any API calls." seems tricky. Maybe you've meant "...more control over the payload OF any API calls."?

KL - Adjusted.

Page 9 - In text "...services implementations are open and interoperable with other..." gaps are really small for me in PDF. Whole part is hard to read.

KL - Adjusted.

Page 11 - Empty line at the top before "The Web Concepts project provides an overview..." seems redundant.

KL - Adjusted.

Page 13 - Part that relates to "Open Data Protocol (OData)" ends up abruptly: "OData
helps you focus on your business logic while building RESTful APIs without having to worry about the ".

KL - Was cut off in formatting - fixed.

Page 14 - Part that relates to "text/tab-separated-values" doesn't end with a period, that is inconsistent with other parts on this page.

KL - Added

Page 16 - Period isn't needed after "Voting Information Project".

KL - Removed

Page 17 - In text "...API Transformer allows anyone to input a API Blueprint, Swagger 1.0 - 1.2, Swagger 2.0 JSON, Swagger 2.0 YAML, WADL - W3C 2009, WSDL - W3C, Google Discovery, RAML 0.8 - 1.0, I/O Docs - Mashery, HAR 1.2, Postman Collection 1.0 - 2.0, Mashape, or APIMATIC Format API definition and then translate and export in a API Blueprint, Swagger 1.0 - 1.2, Swagger 2.0 JSON, Swagger 2.0 YAML, WADL - W3C 2009, RAML 0.8 - 1.0, Postman Collection 1.0 - 2.0, and their own APIMATIC Format...." gaps are really small for me in PDF. Whole part is hard to read.

KL - I took out some of redundancy and gave me padding.

KL - You are the best. I so appreciate you doing this with me...and investing time. Means a lot. Can I cite you in the credits? Any company or project you want me to highlight? Happy to repay!!

Thanks again -- Kin

**Comment by aruckoj** [comment]
Kin, I'm more than happy to help and will be flattered if you cite me.

Your work supports me a lot in familiarization with API world.
Maybe one day company I'm working at right now will also help others and share API Guidelines we're using. But we still need to do a lot before it happens. And you're helping us a lot!

Thanks for continuous sharing of your research and endeavors!
Aleksej
